import { useState } from "react";
import { ChevronLeft, ChevronRight, CheckCircle2, Target, Sparkles, Calendar } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { useScheduledPractice } from "@/hooks/usePracticeZone";
import { usePracticeLogs } from "@/hooks/useUserProgress";
import { useAuth } from "@/components/AuthProvider";
import { useRegenerateWeek } from "@/hooks/useAutoSchedule";
import { useIsMobile } from "@/hooks/use-mobile";
import { format, startOfWeek, endOfWeek, addWeeks, subWeeks, eachDayOfInterval, isSameDay, addDays, subDays } from "date-fns";
import { toast } from "sonner";

interface PracticeWeekViewProps {
  onDateClick: (date: Date, scheduled: any[], practiced: boolean) => void;
  userProfile?: any;
}

export const PracticeWeekView = ({ onDateClick, userProfile }: PracticeWeekViewProps) => {
  const [currentWeek, setCurrentWeek] = useState(new Date());
  const [showFullWeek, setShowFullWeek] = useState(false);
  const { user } = useAuth();
  const isMobile = useIsMobile();
  const { mutate: regenerateWeek, isPending } = useRegenerateWeek();
  
  const weekStart = startOfWeek(currentWeek, { weekStartsOn: 0 });
  const weekEnd = endOfWeek(currentWeek, { weekStartsOn: 0 });
  const weekDays = eachDayOfInterval({ start: weekStart, end: weekEnd });
  
  const { data: scheduled = [], isLoading: scheduledLoading } = useScheduledPractice(
    user?.id,
    format(weekStart, 'yyyy-MM-dd'),
    format(weekEnd, 'yyyy-MM-dd')
  );
  
  const { data: practiceLogs = [], isLoading: logsLoading } = usePracticeLogs(
    user?.id,
    format(weekStart, 'yyyy-MM-dd'),
    format(weekEnd, 'yyyy-MM-dd')
  );
  
  const isLoading = scheduledLoading || logsLoading;

  const getScheduledForDate = (date: Date) => {
    return scheduled.filter(s => {
      const scheduledDate = new Date(s.scheduled_date + 'T00:00:00');
      return isSameDay(scheduledDate, date);
    });
  };

  const isPracticed = (date: Date) => {
    return practiceLogs.some(log => {
      const logDate = new Date(log.practice_date + 'T00:00:00');
      return isSameDay(logDate, date);
    });
  };

  const hasAutoGenerated = (date: Date) => {
    const dayScheduled = getScheduledForDate(date);
    return dayScheduled.some(s => (s as any).auto_generated === true);
  };

  const getVideoTypeIcon = (typeName: string | null) => {
    if (!typeName) return null;
    if (typeName.toLowerCase().includes('instructional')) return '📚';
    if (typeName.toLowerCase().includes('practice')) return '🕺';
    return null;
  };

  const handleRegenerate = () => {
    if (!user?.id) {
      toast.error("Please sign in to regenerate your schedule");
      return;
    }

    const monday = new Date(currentWeek);
    const day = monday.getDay();
    const diff = monday.getDate() - day + (day === 0 ? -6 : 1);
    monday.setDate(diff);
    monday.setHours(0, 0, 0, 0);

    regenerateWeek({ userId: user.id, weekStart: monday });
  };

  const renderDayCard = (day: Date, compact = false) => {
    const dayScheduled = getScheduledForDate(day);
    const dayPracticed = isPracticed(day);
    const isToday = isSameDay(day, new Date());
    const hasAuto = hasAutoGenerated(day);
    const hasScheduled = dayScheduled.length > 0;
    
    const videosByType = dayScheduled.reduce((acc: any, s: any) => {
      const typeName = s.videos?.video_type_mappings?.[0]?.video_types?.name || 'Other';
      const duration = s.videos?.duration || 0;
      if (!acc[typeName]) {
        acc[typeName] = { count: 0, duration: 0, icon: getVideoTypeIcon(typeName) };
      }
      acc[typeName].count++;
      acc[typeName].duration += duration;
      return acc;
    }, {});

    return (
      <button
        key={day.toISOString()}
        onClick={() => onDateClick(day, dayScheduled, dayPracticed)}
        className={`
          relative rounded-lg p-2 flex flex-col items-center justify-start
          transition-all touch-manipulation active:scale-95 w-full
          ${compact ? 'min-h-[140px]' : 'min-h-[140px]'}
          ${isToday && dayPracticed
            ? 'bg-green-500 text-white border-green-600 border-2 shadow-lg hover:bg-green-600'
            : isToday && !dayPracticed
              ? 'bg-blue-500 text-white border-blue-600 border-2 shadow-lg hover:bg-blue-600'
              : dayPracticed 
                ? 'bg-green-500/20 border-green-500/50 border hover:bg-green-500/30'
                : 'bg-card/50 border-border border hover:bg-card hover:border-accent'
          }
        `}
      >
        <span className={`text-xs font-medium ${isToday ? 'opacity-90' : 'text-muted-foreground'}`}>
          {format(day, 'EEE')}
        </span>
        <span className={`text-lg font-bold mb-1`}>
          {format(day, 'd')}
        </span>
        
        {dayScheduled.length > 0 && (
          <div className="flex flex-col gap-1 w-full mt-1">
            {dayScheduled.slice(0, 3).map((scheduled: any) => {
              const video = scheduled.videos;
              const typeName = video?.video_type_mappings?.[0]?.video_types?.name;
              const icon = getVideoTypeIcon(typeName);
              const duration = Math.round((video?.duration || 0) / 60);
              const title = video?.title || 'Untitled';
              const truncatedTitle = compact 
                ? title 
                : title.length > 20 
                  ? title.substring(0, 20) + '...' 
                  : title;
              
              return (
                <div
                  key={scheduled.id}
                  className={`flex flex-col gap-0.5 rounded px-2 py-1 text-xs w-full ${
                    isToday ? 'bg-white/20' : 'bg-background/80'
                  }`}
                >
                  <span className="font-medium truncate text-left">
                    {truncatedTitle}
                  </span>
                  <div className="flex items-center gap-1">
                    <span>{icon}</span>
                    <span className={isToday ? 'opacity-90' : 'text-muted-foreground'}>{duration}m</span>
                  </div>
                </div>
              );
            })}
            {dayScheduled.length > 3 && (
              <div className="text-xs text-muted-foreground text-center mt-0.5">
                +{dayScheduled.length - 3} more
              </div>
            )}
          </div>
        )}
        
        <div className="absolute bottom-1 left-1 flex gap-1 items-center">
          {hasAuto && (
            <Target className="w-3 h-3 text-accent" />
          )}
        </div>
        
        {dayPracticed && (
          <div className="absolute bottom-1 right-1">
            <CheckCircle2 className="w-4 h-4 text-green-500 fill-green-500/20" />
          </div>
        )}
      </button>
    );
  };

  const today = new Date();
  const yesterday = subDays(today, 1);
  const tomorrow = addDays(today, 1);
  const mobileDays = [yesterday, today, tomorrow];

  return (
    <div className="mb-6">
      {/* Week Navigation */}
      <div className="flex items-center justify-between mb-4 gap-2">
        <Button
          variant="ghost"
          size="icon"
          onClick={() => setCurrentWeek(subWeeks(currentWeek, 1))}
          className="shrink-0"
        >
          <ChevronLeft className="w-5 h-5" />
        </Button>
        
        <div className="flex items-center gap-2 min-w-0">
          <h2 className="font-semibold text-sm sm:text-base whitespace-nowrap">
            {format(weekStart, 'MMM d')} - {format(weekEnd, 'MMM d, yyyy')}
          </h2>
          <Button
            onClick={handleRegenerate}
            disabled={isPending}
            variant="outline"
            size="sm"
            className="gap-1.5 shrink-0"
            aria-label="Regenerate practice schedule"
          >
            <Sparkles className="h-3.5 w-3.5" />
            {isPending ? (isMobile ? "..." : "Regenerating...") : (isMobile ? "Refresh" : "Regenerate")}
          </Button>
        </div>
        
        <Button
          variant="ghost"
          size="icon"
          onClick={() => setCurrentWeek(addWeeks(currentWeek, 1))}
          className="shrink-0"
        >
          <ChevronRight className="w-5 h-5" />
        </Button>
      </div>

      {/* Empty Calendar Helper Message */}
      {!isLoading && scheduled.length === 0 && (
        <div className="bg-accent/20 border border-accent rounded-lg p-4 mb-4">
          <p className="text-center font-medium">
            {!userProfile?.dance_role || !userProfile?.skill_level 
              ? "👋 Set your preferences to get started! Look for the settings survey." 
              : "📅 Your calendar is empty. Tap the ✨ Refresh button above to generate your practice schedule!"}
          </p>
        </div>
      )}

      {isLoading ? (
        <div className={isMobile ? "flex gap-2 justify-center" : "grid grid-cols-7 gap-2"}>
          {Array.from({ length: isMobile ? 3 : 7 }).map((_, i) => (
            <Skeleton key={i} className="aspect-square rounded-lg" />
          ))}
        </div>
      ) : isMobile ? (
        <>
          {/* Mobile: 3-Day Carousel View */}
          <div className="relative overflow-hidden -mx-4 px-4">
            <div className="flex gap-3 justify-center items-stretch">
              {mobileDays.map((day, index) => (
                <div
                  key={day.toISOString()}
                  className={`
                    transition-all duration-300
                    ${index === 1 ? 'flex-1 max-w-[200px]' : 'w-20 opacity-50'}
                  `}
                >
                  {renderDayCard(day, index === 1)}
                </div>
              ))}
            </div>
          </div>

          {/* Full Week View Button */}
          <Sheet open={showFullWeek} onOpenChange={setShowFullWeek}>
            <SheetTrigger asChild>
              <Button variant="ghost" className="w-full mt-3 gap-2">
                <Calendar className="w-4 h-4" />
                View Full Week
              </Button>
            </SheetTrigger>
            <SheetContent side="bottom" className="h-[85vh]">
              <SheetHeader>
                <SheetTitle>
                  {format(weekStart, 'MMM d')} - {format(weekEnd, 'MMM d, yyyy')}
                </SheetTitle>
              </SheetHeader>
              <div className="flex flex-col gap-3 mt-6 overflow-y-auto max-h-[calc(85vh-100px)] pb-6">
                {weekDays.map(day => (
                  <div key={day.toISOString()} className="w-full">
                    {renderDayCard(day, true)}
                  </div>
                ))}
              </div>
            </SheetContent>
          </Sheet>
        </>
      ) : (
        /* Desktop: 7-Day Grid */
        <div className="grid grid-cols-7 gap-2">
          {weekDays.map(day => (
            <div key={day.toISOString()}>
              {renderDayCard(day)}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
